### ISSUE TITLE
Allow definition of locations

### ISSUE THREAD

**Issue by p-snft** [mtress/mtress#9]
We had a drafting session how to allow the development of MTRESS to allow a more flexible definition of energy systems. This also solves the problem of various locations where heat can be generated. Note that the code snippets below are based on the dump of the live drafting. They are probably not self-consistent.

The base config might move from json to YAML, as this is more natural for Python users.
```YAML
locations:
  location1:
    air_heat_pump:
      nominal_power: 10 # kW
      ...
    chp:
      nominal_power: 10
  location2:
    - ...

connections:
  - in: location1
    out: location2
    params:
      max: 10
    medium: el
```

The core of the changes in the actual Python code is a proposed base class for (layered heat) techs, that provides a common interface i.e. to bookkeeping of `Flow`s. We also discussed that the focus of the tech classes should be on physics. So, information on funding schemes, investment costs and other things that can change very often and between locations should not not be part of the classes.

```Python
class CHP(GenericTechnology):

  def __init__(self, **kwargs):
    ...
    self._nominal_power = kwargs.get('nominal_power')
    self._flows = {}

    ...

    chp = GenericCHP(...self._nominal_power)

    es.add(bus, chp)

  @property
  def flows(self):
    return self._flows


def Metamodel:

  def __init__(self, sim_config):
    self._location = dict()
    for location in sim_config.params:
      self._location[location] = set()
      for tech_type in sim_config.params[location]:
        cls = get_class_for_tech(tech_type)
        for tech_system in sim_config.params[location][tech_type]:
          self._locations[location].add(cls(sim_config.params[location][tech_type][tech_system], energy_system, **kwargs))

  def kpi1(self):
    for tech in self._techs:
      tech.flows ...

```
